<?php

namespace BurgundyWineSchool\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends EntityRepository
{
}
