BurgundyWineSchool\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: BurgundyWineSchool\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    lifecycleCallbacks: {  }
